#!/usr/bin/awk -f
#
# Extract bidirectional flow features from packet records generated by tshark.
#
# Input format (comma-separated):
#   frame.time_epoch, ip.src, ip.dst, tcp.srcport, tcp.dstport,
#   udp.srcport, udp.dstport, frame.len, ip.proto
#
# Output format:
#   Semicolon-separated flow records with aggregate variables and
#   eight-bin histograms for packet size and inter-packet time (IPT).
#
# The two endpoints of each flow are ordered lexicographically to obtain a
# deterministic bidirectional identifier. Consequently, "fwd" and "bwd"
# represent that canonical orientation.

BEGIN {
  FS = ","
  OFS = ";"
  NBINS = 8

  print "flow_id;proto;duration;bytes_fwd;pkts_fwd;bytes_bwd;pkts_bwd" \
        ";fwd_size_bin1;fwd_size_bin2;fwd_size_bin3;fwd_size_bin4;fwd_size_bin5;fwd_size_bin6;fwd_size_bin7;fwd_size_bin8" \
        ";bwd_size_bin1;bwd_size_bin2;bwd_size_bin3;bwd_size_bin4;bwd_size_bin5;bwd_size_bin6;bwd_size_bin7;bwd_size_bin8" \
        ";fwd_ipt_bin1;fwd_ipt_bin2;fwd_ipt_bin3;fwd_ipt_bin4;fwd_ipt_bin5;fwd_ipt_bin6;fwd_ipt_bin7;fwd_ipt_bin8" \
        ";bwd_ipt_bin1;bwd_ipt_bin2;bwd_ipt_bin3;bwd_ipt_bin4;bwd_ipt_bin5;bwd_ipt_bin6;bwd_ipt_bin7;bwd_ipt_bin8"
}

function bin8(x) {
  if (x <= 15) return 1
  else if (x <= 31) return 2
  else if (x <= 63) return 3
  else if (x <= 127) return 4
  else if (x <= 255) return 5
  else if (x <= 511) return 6
  else if (x <= 1024) return 7
  else return 8
}

function protocol_name(protocol_number) {
  if (protocol_number == 6) return "tcp"
  if (protocol_number == 17) return "udp"
  return "ip" protocol_number
}

function set_flow_orientation(src, dst, src_port, dst_port, protocol_number,
                              endpoint_a, endpoint_b, protocol) {
  protocol = protocol_name(protocol_number)
  endpoint_a = src ":" src_port
  endpoint_b = dst ":" dst_port

  if (endpoint_a < endpoint_b) {
    FLOW_ID = protocol "|" endpoint_a "-" endpoint_b
    DIRECTION = "fwd"
  } else {
    FLOW_ID = protocol "|" endpoint_b "-" endpoint_a
    DIRECTION = "bwd"
  }
  FLOW_PROTOCOL = protocol
}

NR == 1 { next }  # Skip the tshark header.

{
  timestamp = $1 + 0
  src = $2
  dst = $3
  tcp_src_port = $4
  tcp_dst_port = $5
  udp_src_port = $6
  udp_dst_port = $7
  packet_length = $8 + 0
  protocol_number = $9 + 0

  src_port = (tcp_src_port != "") ? tcp_src_port : udp_src_port
  dst_port = (tcp_dst_port != "") ? tcp_dst_port : udp_dst_port
  if (src_port == "" || dst_port == "") next

  set_flow_orientation(src, dst, src_port, dst_port, protocol_number)
  flow = FLOW_ID
  direction = DIRECTION

  if (!(flow in start_timestamp) || timestamp < start_timestamp[flow]) {
    start_timestamp[flow] = timestamp
  }
  if (!(flow in end_timestamp) || timestamp > end_timestamp[flow]) {
    end_timestamp[flow] = timestamp
  }

  bytes[flow, direction] += packet_length
  packets[flow, direction]++

  size_bin = bin8(packet_length)
  size_histogram[flow, direction, size_bin]++

  direction_key = flow SUBSEP direction
  if (direction_key in last_timestamp) {
    ipt_ms = (timestamp - last_timestamp[direction_key]) * 1000.0
    if (ipt_ms < 0) ipt_ms = 0
    ipt_bin = bin8(ipt_ms)
    ipt_histogram[flow, direction, ipt_bin]++
  }
  last_timestamp[direction_key] = timestamp
  protocols[flow] = FLOW_PROTOCOL
}

END {
  for (flow in start_timestamp) {
    duration = end_timestamp[flow] - start_timestamp[flow]
    if (duration < 0) duration = 0

    fwd_bytes = bytes[flow, "fwd"] + 0
    fwd_packets = packets[flow, "fwd"] + 0
    bwd_bytes = bytes[flow, "bwd"] + 0
    bwd_packets = packets[flow, "bwd"] + 0

    printf "%s;%s;%.6f;%d;%d;%d;%d", flow, protocols[flow], duration, \
           fwd_bytes, fwd_packets, bwd_bytes, bwd_packets

    for (i = 1; i <= NBINS; i++) printf ";%d", size_histogram[flow, "fwd", i] + 0
    for (i = 1; i <= NBINS; i++) printf ";%d", size_histogram[flow, "bwd", i] + 0
    for (i = 1; i <= NBINS; i++) printf ";%d", ipt_histogram[flow, "fwd", i] + 0
    for (i = 1; i <= NBINS; i++) printf ";%d", ipt_histogram[flow, "bwd", i] + 0

    printf "\n"
  }
}
